# Generated by Django 5.1.1 on 2024-09-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_admin_funcionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
