# Generated by Django 5.1.2 on 2024-11-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0006_funcionario_delete_contact_delete_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descrição',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='preço',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantidade',
        ),
    ]
