# Generated by Django 5.1.2 on 2024-11-28 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0010_alter_solicitation_data_solicitacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitation',
            old_name='data_solicitacao',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='solicitation',
            old_name='quantidade_solicitada',
            new_name='quantidade',
        ),
        migrations.RemoveField(
            model_name='solicitation',
            name='data_resolucao',
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelf.product'),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('negada', 'Negada')], default='pendente', max_length=20),
        ),
    ]
