# Generated by Django 5.1.2 on 2024-12-03 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0011_rename_data_solicitacao_solicitation_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aceita', 'Aceita'), ('Negada', 'Negada')], default='Pendente', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelf.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Solicitation',
        ),
    ]
