# Generated by Django 5.1.2 on 2024-12-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0012_productrequest_delete_solicitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='destinatario',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
