# Generated by Django 5.1.2 on 2024-12-05 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0013_productrequest_destinatario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producthistory',
            old_name='quantidade_retirada',
            new_name='quantidade',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='data_retirada',
        ),
        migrations.AddField(
            model_name='producthistory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producthistory',
            name='destinatario',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producthistory',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelf.product'),
        ),
    ]
