# Generated by Django 5.1.2 on 2024-12-05 11:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0014_rename_quantidade_retirada_producthistory_quantidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producthistory',
            old_name='quantidade',
            new_name='quantidade_retirada',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='tipo',
        ),
        migrations.AddField(
            model_name='producthistory',
            name='data_retirada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='shelf.product'),
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=10)),
                ('quantidade', models.IntegerField()),
                ('destinatario', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelf.product')),
            ],
        ),
    ]
