# Generated by Django 5.1.2 on 2024-12-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0015_rename_quantidade_producthistory_quantidade_retirada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatorio',
            old_name='date_created',
            new_name='data_retirada',
        ),
    ]
