# Generated by Django 5.1.2 on 2024-12-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0016_rename_date_created_relatorio_data_retirada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relatorio',
        ),
    ]
